### ISSUE TITLE
he's defo gonna slow down the timer so his runs look better smh 

### ISSUE THREAD

**Issue by Declanjsy** [AkaFletch/gosplit#1]
Cheating in a Super Mario 64 16 star speed run is unacceptable. This game is a classic, and cheating in a speed run undermines the integrity of the game and the speed running community. The entire point of a speed run is to see how fast you can complete the game without cheating. Specific splits like Bomb Clip, Whomp's Fortress, and MIPS the rabbit are crucial to the 16 star category, and cheating in any of them is just plain lazy. Cheating not only cheats yourself out of the satisfaction of completing the game legitimately but also wastes everyone's time, including those who watch your speed run. If you can't complete the game without cheating, then don't bother playing it at all.

**Comment by AkaFletch** [comment]
I wouldn't worry about it

**Comment by Declanjsy** [comment]
:nerd_face:
